[aws]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[character]
success_symbol = "[λ](bold #98beba)"
error_symbol = "[λ](bold #e68183)"
vicmd_symbol = "[λ](bold #868d80)"

[cmake]
disabled = true

[cmd_duration]
format = " [$duration](italic #d3a0bc)"

[directory]
truncation_length = 8
truncation_symbol = "…/"
style = "normal #87c095"

[gcloud]
disabled = true

[git_branch]
symbol = "🌱 "
style = "italic #d3a0bc"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[package]
format = "is [🎁 $version](bold 208) "
