[aws]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[character]
symbol = "λ"
vicmd_symbol = "ƛ"
use_symbol_for_status = false
style_success = "bold blue"
style_failure = "bold red"

[cmd_duration]
prefix = ""
style = "italic dimmed white"

[conda]
symbol = " "

[directory]
prefix = ""
fish_style_pwd_dir_length = 3
style = "bold italic cyan"

[docker_context]
disabled = false

[dotnet]
symbol = "🥅 "

[git_branch]
symbol = "🌱 "
style = "bold italic purple"

[git_state]
cherry_pick = "🍒 PICKING"
style = "bold italic yellow"

[git_status]
conflicted = "🏳"
conflicted_count.enabled = true
ahead = "💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
untracked_count.enabled = true
stashed = "🗃"
modified = "✏"
staged = "🙏"
staged_count.enabled = true
renamed = "👅"
renamed_count.enabled = true
deleted = "🗑"
deleted_count.enabled = true

[memory_usage]
disabled = false
style = "bold dimmed italic white"

[nodejs]
symbol = "🤖 "
style = "bold italic green"

[hg_branch]
symbol = "🌱 "

[hostname]
style = "bold dimmed italic green"

[jobs]
disabled = true

[package]
symbol = "🎁 "
style = "bold orange"

[python]
pyenv_prefix = ""
style = "bold italic yellow"

[time]
format = "🕙 %T "
style = "bold italic yellow"

[username]
style_root = "bold italic red"
style_user = "bold italic yellow"
